tags:
- name: "exercises"
  description: "Operations about exercises"
  
paths:
# [GET] exercises
  /exercises/{id}:
    get:
      tags:
      - "exercises"
      summary: "Get exercise by Id"
      parameters: 
      - name: "id"
        in: "path"
        description: "Id of exercise to return"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
        404:
          description: "Exercise not found"
        500:
          description: "Server error"